// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceShips.Data;

namespace SpaceShips.Data.Migrations
{
    [DbContext(typeof(SpaceShipsDbContext))]
    partial class SpaceShipsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpaceShips.Data.Models.SpaceShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("YearStartSpace")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SpaceShips");
                });

            modelBuilder.Entity("SpaceShips.Data.Models.SpaceTransferFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LightMilesTraveled")
                        .HasColumnType("int");

                    b.Property<int>("SpaceShipId")
                        .HasColumnType("int");

                    b.Property<int>("YearOfPurchase")
                        .HasColumnType("int");

                    b.Property<int>("YearOfTaxCalculation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpaceShipId");

                    b.ToTable("SpaceTransferFees");
                });

            modelBuilder.Entity("SpaceShips.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SpaceShips.Data.Models.SpaceShip", b =>
                {
                    b.HasOne("SpaceShips.Data.Models.User", "User")
                        .WithMany("SpeceShips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpaceShips.Data.Models.SpaceTransferFee", b =>
                {
                    b.HasOne("SpaceShips.Data.Models.SpaceShip", "SpaceShip")
                        .WithMany("SpaceTransferFees")
                        .HasForeignKey("SpaceShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpaceShip");
                });

            modelBuilder.Entity("SpaceShips.Data.Models.SpaceShip", b =>
                {
                    b.Navigation("SpaceTransferFees");
                });

            modelBuilder.Entity("SpaceShips.Data.Models.User", b =>
                {
                    b.Navigation("SpeceShips");
                });
#pragma warning restore 612, 618
        }
    }
}
